# Generated by Django 5.1.2 on 2024-10-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0003_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
