# Generated by Django 5.1.2 on 2024-10-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0004_pacientes_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArea', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pacientes',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='EsAbDeApp.areas'),
        ),
    ]
