# Generated by Django 5.1.2 on 2024-10-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0005_areas_pacientes_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
