# Generated by Django 5.1.2 on 2024-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0006_areas_description_areas_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='area',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='EsAbDeApp.areas'),
        ),
    ]
