# Generated by Django 5.1.2 on 2024-10-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0007_remove_pacientes_area_pacientes_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='EsAbDeApp.agerange')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='EsAbDeApp.areas')),
            ],
        ),
    ]
