# Generated by Django 5.1.2 on 2024-10-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0008_agerange_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsAbDeApp.areas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsAbDeApp.pacientes')),
            ],
        ),
    ]
