# Generated by Django 5.1.2 on 2024-10-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0009_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsAbDeApp.areas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsAbDeApp.pacientes')),
            ],
        ),
    ]
