# Generated by Django 5.1.2 on 2024-11-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0010_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='EsAbDeApp.areas'),
        ),
    ]
