# Generated by Django 5.1.2 on 2024-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsAbDeApp', '0011_alter_respuesta_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
